export const registeredSemesters = [
  {
    id: "2023-2024-2",
    title: "2023/2024 2nd Semester",
    status: "Current",
    creditLoad: 17,
    courses: [
      {
        code: "AGE405",
        title: "Farm Power & Machinery",
        lecturer: "Dr. A. O. Adejumo",
        units: 3,
        semester: 2,
        grade: "A",
        status: "In Progress",
      },
      {
        code: "AGE412",
        title: "Soil & Water Conservation",
        lecturer: "Prof. M. B. Idowu",
        units: 3,
        semester: 2,
        grade: "B+",
        status: "In Progress",
      },
      {
        code: "AGE416",
        title: "Project (Research)",
        lecturer: "Dr. K. T. Oladimeji",
        units: 6,
        semester: 2,
        grade: "A",
        status: "In Progress",
      },
      {
        code: "AGE412",
        title: "Soil & Water Conservation",
        lecturer: "Prof. M. B. Idowu",
        units: 3,
        semester: 2,
        grade: "B+",
        status: "In Progress",
      },
      {
        code: "AGE416",
        title: "Project (Research)",
        lecturer: "Dr. K. T. Oladimeji",
        units: 6,
        semester: 2,
        grade: "A",
        status: "In Progress",
      },
      {
        code: "AGE412",
        title: "Soil & Water Conservation",
        lecturer: "Prof. M. B. Idowu",
        units: 3,
        semester: 2,
        grade: "B+",
        status: "In Progress",
      },
      {
        code: "AGE416",
        title: "Project (Research)",
        lecturer: "Dr. K. T. Oladimeji",
        units: 6,
        semester: 2,
        grade: "A",
        status: "In Progress",
      },
    ],
  },
  {
    id: "2023-2024-1",
    title: "2023/2024 1st Semester",
    status: "Completed",
    creditLoad: 18,
    courses: [
      {
        code: "AGE301",
        title: "Agricultural Economics",
        lecturer: "Dr. S. O. Ojo",
        units: 3,
        semester: 1,
        grade: "A",
        status: "Completed",
      },
      {
        code: "STA301",
        title: "Statistics for Engineers",
        lecturer: "Prof. A. B. Lawal",
        units: 3,
        semester: 1,
        grade: "B+",
        status: "Completed",
      },
      {
        code: "AGE412",
        title: "Soil & Water Conservation",
        lecturer: "Prof. M. B. Idowu",
        units: 3,
        semester: 2,
        grade: "B+",
        status: "Dropped",
      },
      {
        code: "AGE416",
        title: "Project (Research)",
        lecturer: "Dr. K. T. Oladimeji",
        units: 6,
        semester: 2,
        grade: "A",
        status: "Completed",
      },
      {
        code: "AGE412",
        title: "Soil & Water Conservation",
        lecturer: "Prof. M. B. Idowu",
        units: 3,
        semester: 2,
        grade: "B+",
        status: "Dropped",
      },
      {
        code: "AGE416",
        title: "Project (Research)",
        lecturer: "Dr. K. T. Oladimeji",
        units: 6,
        semester: 2,
        grade: "A",
        status: "Completed",
      },
    ],
  },
  {
    id: "2022-2023-2",
    title: "2022/2023 2nd Semester",
    status: "Completed",
    creditLoad: 17,
    courses: [
      {
        code: "AGE412",
        title: "Soil & Water Conservation",
        lecturer: "Prof. M. B. Idowu",
        units: 3,
        semester: 2,
        grade: "B+",
        status: "Completed",
      },
      {
        code: "AGE416",
        title: "Project (Research)",
        lecturer: "Dr. K. T. Oladimeji",
        units: 6,
        semester: 2,
        grade: "A",
        status: "Completed",
      },
      {
        code: "AGE412",
        title: "Soil & Water Conservation",
        lecturer: "Prof. M. B. Idowu",
        units: 3,
        semester: 2,
        grade: "B+",
        status: "Completed",
      },
      {
        code: "AGE416",
        title: "Project (Research)",
        lecturer: "Dr. K. T. Oladimeji",
        units: 6,
        semester: 2,
        grade: "A",
        status: "Completed",
      },
      {
        code: "AGE412",
        title: "Soil & Water Conservation",
        lecturer: "Prof. M. B. Idowu",
        units: 3,
        semester: 2,
        grade: "B+",
        status: "Completed",
      },
      {
        code: "AGE416",
        title: "Project (Research)",
        lecturer: "Dr. K. T. Oladimeji",
        units: 6,
        semester: 2,
        grade: "A",
        status: "Dropped",
      },
    ],
  },
];
