export const recentResults = [
  {
    code: "AGE 401",
    course: "Farm Power & Machinery",
    unit: 3,
    score: 78,
    grade: "A",
    status: "Passed",
  },
  {
    code: "AGE 403",
    course: "Soil & Water Engineering",
    unit: 3,
    score: 72,
    grade: "A",
    status: "Passed",
  },
  {
    code: "AGE 405",
    course: "Irrigation Engineering",
    unit: 2,
    score: 69,
    grade: "B",
    status: "Passed",
  },
  {
    code: "AGE 407",
    course: "Agricultural Structures",
    unit: 3,
    score: 81,
    grade: "A",
    status: "Passed",
  },
  {
    code: "AGE 409",
    course: "Engineering Seminar",
    unit: 1,
    score: 85,
    grade: "A",
    status: "Passed",
  },
  {
    code: "AGE 409",
    course: "Engineering Seminar",
    unit: 1,
    score: 85,
    grade: "A",
    status: "Passed",
  },
  {
    code: "AGE 409",
    course: "Engineering Seminar",
    unit: 1,
    score: 85,
    grade: "A",
    status: "Passed",
  },
  {
    code: "AGE 409",
    course: "Engineering Seminar",
    unit: 1,
    score: 85,
    grade: "A",
    status: "Passed",
  },
  {
    code: "AGE 409",
    course: "Engineering Seminar",
    unit: 1,
    score: 85,
    grade: "A",
    status: "Passed",
  },
  {
    code: "AGE 409",
    course: "Engineering Seminar",
    unit: 1,
    score: 85,
    grade: "A",
    status: "Passed",
  },
];
