import { BookOpen, CheckCircle, GraduationCap, Clock3 } from "lucide-react";

export const courseFilters = {
  departments: [
    { value: "", label: "All Departments" },
    { value: "Agricultural Engineering", label: "Agricultural Engineering" },
    { value: "Civil Engineering", label: "Civil Engineering" },
    { value: "Mechanical Engineering", label: "Mechanical Engineering" },
    { value: "Electrical Engineering", label: "Electrical Engineering" },
    { value: "Computer Engineering", label: "Computer Engineering" },
  ],

  levels: [
    { value: "", label: "All Levels" },
    { value: "100", label: "100 Level" },
    { value: "200", label: "200 Level" },
    { value: "300", label: "300 Level" },
    { value: "400", label: "400 Level" },
    { value: "500", label: "500 Level" },
  ],

  semesters: [
    { value: "", label: "All Semesters" },
    { value: "First", label: "First Semester" },
    { value: "Second", label: "Second Semester" },
  ],

  statuses: [
    { value: "", label: "All Status" },
    { value: "Active", label: "Active" },
    { value: "Inactive", label: "Inactive" },
  ],
};

export const courses = [
  {
    id: 1,
    code: "AGE401",
    title: "Soil Mechanics",
    unit: 3,
    level: "400",
    semester: "First",
    department: "Agricultural Engineering",
    lecturer: "Dr. Adebisi",
    status: "Active",
  },
  {
    id: 2,
    code: "AGE403",
    title: "Irrigation Engineering",
    unit: 3,
    level: "400",
    semester: "First",
    department: "Agricultural Engineering",
    lecturer: "Dr. Akinola",
    status: "Active",
  },
  {
    id: 3,
    code: "AGE405",
    title: "Farm Power & Machinery",
    unit: 3,
    level: "400",
    semester: "Second",
    department: "Agricultural Engineering",
    lecturer: "Dr. Ogunleye",
    status: "Active",
  },
  {
    id: 4,
    code: "CIV301",
    title: "Structural Analysis",
    unit: 3,
    level: "300",
    semester: "First",
    department: "Civil Engineering",
    lecturer: "Dr. Okonkwo",
    status: "Active",
  },
  {
    id: 5,
    code: "CIV305",
    title: "Reinforced Concrete",
    unit: 3,
    level: "300",
    semester: "Second",
    department: "Civil Engineering",
    lecturer: "Dr. Ibrahim",
    status: "Active",
  },
  {
    id: 6,
    code: "MEC401",
    title: "Machine Design",
    unit: 3,
    level: "400",
    semester: "First",
    department: "Mechanical Engineering",
    lecturer: "Dr. Hassan",
    status: "Active",
  },
  {
    id: 7,
    code: "MEC405",
    title: "Thermodynamics II",
    unit: 3,
    level: "400",
    semester: "Second",
    department: "Mechanical Engineering",
    lecturer: "Dr. Bello",
    status: "Active",
  },
  {
    id: 8,
    code: "EEE401",
    title: "Power Systems",
    unit: 3,
    level: "400",
    semester: "First",
    department: "Electrical Engineering",
    lecturer: "Dr. Nwosu",
    status: "Active",
  },
  {
    id: 9,
    code: "EEE405",
    title: "Control Engineering",
    unit: 3,
    level: "400",
    semester: "Second",
    department: "Electrical Engineering",
    lecturer: "Dr. Okoro",
    status: "Active",
  },
  {
    id: 10,
    code: "CPE201",
    title: "Programming II",
    unit: 3,
    level: "200",
    semester: "First",
    department: "Computer Engineering",
    lecturer: "Dr. Adeyemi",
    status: "Active",
  },
  {
    id: 11,
    code: "CPE301",
    title: "Data Structures",
    unit: 3,
    level: "300",
    semester: "First",
    department: "Computer Engineering",
    lecturer: "Dr. Yusuf",
    status: "Active",
  },
  {
    id: 12,
    code: "CPE401",
    title: "Computer Networks",
    unit: 3,
    level: "400",
    semester: "Second",
    department: "Computer Engineering",
    lecturer: "Dr. Olatunji",
    status: "Active",
  },
  {
    id: 13,
    code: "GES101",
    title: "Communication in English",
    unit: 2,
    level: "100",
    semester: "First",
    department: "General Studies",
    lecturer: "Dr. Williams",
    status: "Active",
  },
  {
    id: 14,
    code: "MTH201",
    title: "Engineering Mathematics",
    unit: 3,
    level: "200",
    semester: "First",
    department: "General Studies",
    lecturer: "Dr. Ajayi",
    status: "Active",
  },
  {
    id: 15,
    code: "STA201",
    title: "Engineering Statistics",
    unit: 2,
    level: "200",
    semester: "Second",
    department: "General Studies",
    lecturer: "Dr. Lawal",
    status: "Pending",
  },
];
