import {
  Users,
  BookOpen,
  UserPlus,
  Upload,
  Building2,
  BarChart3,
  FileSpreadsheet,
  FileText,
  GraduationCap,
} from "lucide-react";

export const dashboardStats = [
  {
    id: 1,
    title: "Total Students",
    value: "1,248",
    subtitle: "+24 this session",
    icon: Users,
    color: "blue",
  },
  {
    id: 2,
    title: "Courses",
    value: "84",
    subtitle: "Across all departments",
    icon: BookOpen,
    color: "green",
  },
  {
    id: 3,
    title: "Departments",
    value: "12",
    subtitle: "Active departments",
    icon: Building2,
    color: "purple",
  },
  {
    id: 4,
    title: "Pending Results",
    value: "48",
    subtitle: "Awaiting approval",
    icon: FileText,
    color: "amber",
  },
];

export const dashboardQuickActions = [
  {
    title: "Add Student",
    description: "Register a new student",
    icon: UserPlus,
    color: "blue",
    path: "/admin/students/add",
  },
  {
    title: "Upload Results",
    description: "Upload semester results",
    icon: Upload,
    color: "green",
    path: "/admin/results",
  },
  {
    title: "Manage Courses",
    description: "Create and edit courses",
    icon: BookOpen,
    color: "orange",
    path: "/admin/courses",
  },
  {
    title: "Departments",
    description: "Manage departments",
    icon: Building2,
    color: "purple",
    path: "/admin/departments",
  },
  {
    title: "Analytics",
    description: "View reports",
    icon: BarChart3,
    color: "indigo",
    path: "/admin/analytics",
  },
  {
    title: "Export Data",
    description: "Download reports",
    icon: FileSpreadsheet,
    color: "rose",
    path: "#",
  },
];

export const recentStudents = [
  {
    id: 1,
    matricNumber: "20/ENG/0400",
    fullName: "Ademola Oyelusi",
    department: "Agricultural Engineering",
    level: "400",
    status: "Active",
  },
  {
    id: 2,
    matricNumber: "21/CSC/0102",
    fullName: "John Samuel",
    department: "Computer Science",
    level: "300",
    status: "Active",
  },
  {
    id: 3,
    matricNumber: "22/MCB/0205",
    fullName: "Grace Williams",
    department: "Microbiology",
    level: "200",
    status: "Pending",
  },
  {
    id: 4,
    matricNumber: "20/CVE/0145",
    fullName: "David Johnson",
    department: "Civil Engineering",
    level: "400",
    status: "Active",
  },
  {
    id: 5,
    matricNumber: "23/EEE/0009",
    fullName: "Mary Peter",
    department: "Electrical Engineering",
    level: "100",
    status: "Pending",
  },
];

export const pendingResults = [
  {
    id: 1,
    courseCode: "AGE401",
    courseTitle: "Farm Power and Machinery",
    department: "Agricultural Engineering",
    level: "400",
    lecturer: "Dr. A. Bello",
    status: "Pending Upload",
  },
  {
    id: 2,
    courseCode: "CSC305",
    courseTitle: "Database Systems",
    department: "Computer Science",
    level: "300",
    lecturer: "Prof. O. James",
    status: "Awaiting Approval",
  },
  {
    id: 3,
    courseCode: "EEE402",
    courseTitle: "Power Systems",
    department: "Electrical Engineering",
    level: "400",
    lecturer: "Dr. Musa",
    status: "Pending Upload",
  },
  {
    id: 4,
    courseCode: "MCB301",
    courseTitle: "Medical Microbiology",
    department: "Microbiology",
    level: "300",
    lecturer: "Dr. Adeyemi",
    status: "Approved",
  },
];

export const departmentOverview = [
  {
    id: 1,
    name: "Agricultural Engineering",
    students: 182,
    lecturers: 18,
    courses: 42,
    completion: 82,
  },
  {
    id: 2,
    name: "Computer Science",
    students: 326,
    lecturers: 25,
    courses: 56,
    completion: 65,
  },
  {
    id: 3,
    name: "Civil Engineering",
    students: 144,
    lecturers: 16,
    courses: 38,
    completion: 95,
  },
  {
    id: 4,
    name: "Electrical Engineering",
    students: 215,
    lecturers: 20,
    courses: 47,
    completion: 60,
  },
  {
    id: 5,
    name: "Microbiology",
    students: 198,
    lecturers: 19,
    courses: 44,
    completion: 73,
  },
];

export const upcomingActivities = [
  {
    id: 1,
    title: "Course Registration Closes",
    date: "15 Aug",
    icon: BookOpen,
    color: "blue",
  },
  {
    id: 2,
    title: "Result Upload Deadline",
    date: "18 Aug",
    icon: Upload,
    color: "green",
  },
  {
    id: 3,
    title: "Senate Approval Meeting",
    date: "21 Aug",
    icon: Users,
    color: "orange",
  },
  {
    id: 4,
    title: "New Academic Session Begins",
    date: "25 Aug",
    icon: GraduationCap,
    color: "purple",
  },
];
