import { Users, UserCheck, GraduationCap, UserX } from "lucide-react";

export const studentStatistics = [
  {
    title: "Total Students",
    value: 1248,
    change: "+18",
    description: "Compared to last session",
    icon: Users,
    color: "blue",
  },
  {
    title: "Active Students",
    value: 1132,
    change: "+12",
    description: "Currently enrolled",
    icon: UserCheck,
    color: "green",
  },
  {
    title: "Graduated",
    value: 96,
    change: "+25",
    description: "This academic year",
    icon: GraduationCap,
    color: "purple",
  },
  {
    title: "Suspended",
    value: 20,
    change: "-3",
    description: "Disciplinary cases",
    icon: UserX,
    color: "red",
  },
];

export const studentFilters = {
  departments: [
    {
      value: "",
      label: "All Departments",
    },
    {
      value: "Agricultural Engineering",
      label: "Agricultural Engineering",
    },
    {
      value: "Computer Science",
      label: "Computer Science",
    },
    {
      value: "Civil Engineering",
      label: "Civil Engineering",
    },
    {
      value: "Electrical Engineering",
      label: "Electrical Engineering",
    },
    {
      value: "Microbiology",
      label: "Microbiology",
    },
  ],

  levels: [
    {
      value: "",
      label: "All Levels",
    },
    {
      value: "100",
      label: "100 Level",
    },
    {
      value: "200",
      label: "200 Level",
    },
    {
      value: "300",
      label: "300 Level",
    },
    {
      value: "400",
      label: "400 Level",
    },
    {
      value: "500",
      label: "500 Level",
    },
  ],

  statuses: [
    {
      value: "",
      label: "All Status",
    },
    {
      value: "Active",
      label: "Active",
    },
    {
      value: "Graduated",
      label: "Graduated",
    },
    {
      value: "Deferred",
      label: "Deferred",
    },
    {
      value: "Suspended",
      label: "Suspended",
    },
    {
      value: "Withdrawn",
      label: "Withdrawn",
    },
  ],
};

export const students = [
  {
    id: 1,
    matricNumber: "20/ENG/0400",
    fullName: "Ademola Oyelusi",
    email: "ademola.oyelusi@gradehub.edu.ng",
    department: "Agricultural Engineering",
    level: "400",
    status: "Active",
    cgpa: "4.62",
  },
  {
    id: 2,
    matricNumber: "20/CSC/0145",
    fullName: "Aisha Bello",
    email: "aisha.bello@gradehub.edu.ng",
    department: "Computer Science",
    level: "400",
    status: "Active",
    cgpa: "4.88",
  },
  {
    id: 3,
    matricNumber: "19/CVE/0128",
    fullName: "John Okafor",
    email: "john.okafor@gradehub.edu.ng",
    department: "Civil Engineering",
    level: "500",
    status: "Graduated",
    cgpa: "4.31",
  },
  {
    id: 4,
    matricNumber: "21/MCB/0062",
    fullName: "Grace Adeyemi",
    email: "grace.adeyemi@gradehub.edu.ng",
    department: "Microbiology",
    level: "300",
    status: "Deferred",
    cgpa: "3.71",
  },
  {
    id: 4,
    matricNumber: "21/MCB/0062",
    fullName: "Grace Adeyemi",
    email: "grace.adeyemi@gradehub.edu.ng",
    department: "Microbiology",
    level: "300",
    status: "Deferred",
    cgpa: "3.71",
  },
  {
    id: 4,
    matricNumber: "21/MCB/0062",
    fullName: "Grace Adeyemi",
    email: "grace.adeyemi@gradehub.edu.ng",
    department: "Microbiology",
    level: "300",
    status: "Deferred",
    cgpa: "3.71",
  },
  {
    id: 4,
    matricNumber: "21/MCB/0062",
    fullName: "Grace Adeyemi",
    email: "grace.adeyemi@gradehub.edu.ng",
    department: "Microbiology",
    level: "300",
    status: "Deferred",
    cgpa: "3.71",
  },
  {
    id: 4,
    matricNumber: "21/MCB/0062",
    fullName: "Grace Adeyemi",
    email: "grace.adeyemi@gradehub.edu.ng",
    department: "Microbiology",
    level: "300",
    status: "Deferred",
    cgpa: "3.71",
  },
  {
    id: 4,
    matricNumber: "21/MCB/0062",
    fullName: "Grace Adeyemi",
    email: "grace.adeyemi@gradehub.edu.ng",
    department: "Microbiology",
    level: "300",
    status: "Deferred",
    cgpa: "3.71",
  },
  {
    id: 4,
    matricNumber: "21/MCB/0062",
    fullName: "Grace Adeyemi",
    email: "grace.adeyemi@gradehub.edu.ng",
    department: "Microbiology",
    level: "300",
    status: "Deferred",
    cgpa: "3.71",
  },
  {
    id: 4,
    matricNumber: "21/MCB/0062",
    fullName: "Grace Adeyemi",
    email: "grace.adeyemi@gradehub.edu.ng",
    department: "Microbiology",
    level: "300",
    status: "Deferred",
    cgpa: "3.71",
  },
  {
    id: 4,
    matricNumber: "21/MCB/0062",
    fullName: "Grace Adeyemi",
    email: "grace.adeyemi@gradehub.edu.ng",
    department: "Microbiology",
    level: "300",
    status: "Deferred",
    cgpa: "3.71",
  },
  {
    id: 4,
    matricNumber: "21/MCB/0062",
    fullName: "Grace Adeyemi",
    email: "grace.adeyemi@gradehub.edu.ng",
    department: "Microbiology",
    level: "300",
    status: "Deferred",
    cgpa: "3.71",
  },
  {
    id: 4,
    matricNumber: "21/MCB/0062",
    fullName: "Grace Adeyemi",
    email: "grace.adeyemi@gradehub.edu.ng",
    department: "Microbiology",
    level: "300",
    status: "Deferred",
    cgpa: "3.71",
  },
  {
    id: 4,
    matricNumber: "21/MCB/0062",
    fullName: "Grace Adeyemi",
    email: "grace.adeyemi@gradehub.edu.ng",
    department: "Microbiology",
    level: "300",
    status: "Deferred",
    cgpa: "3.71",
  },
  {
    id: 4,
    matricNumber: "21/MCB/0062",
    fullName: "Grace Adeyemi",
    email: "grace.adeyemi@gradehub.edu.ng",
    department: "Microbiology",
    level: "300",
    status: "Deferred",
    cgpa: "3.71",
  },
];
