import { Users, UserCheck, GraduationCap, UserX } from "lucide-react";

export const studentStatistics = [
  {
    title: "Total Students",
    value: 1248,
    change: "+18",
    description: "Compared to last session",
    icon: Users,
    color: "blue",
  },
  {
    title: "Active Students",
    value: 1132,
    change: "+12",
    description: "Currently enrolled",
    icon: UserCheck,
    color: "green",
  },
  {
    title: "Graduated",
    value: 96,
    change: "+25",
    description: "This academic year",
    icon: GraduationCap,
    color: "purple",
  },
  {
    title: "Suspended",
    value: 20,
    change: "-3",
    description: "Disciplinary cases",
    icon: UserX,
    color: "red",
  },
];

export const studentFilters = {
  departments: [
    {
      value: "",
      label: "All Departments",
    },
    {
      value: "Agricultural Engineering",
      label: "Agricultural Engineering",
    },
    {
      value: "Computer Science",
      label: "Computer Science",
    },
    {
      value: "Civil Engineering",
      label: "Civil Engineering",
    },
    {
      value: "Electrical Engineering",
      label: "Electrical Engineering",
    },
    {
      value: "Microbiology",
      label: "Microbiology",
    },
  ],

  levels: [
    {
      value: "",
      label: "All Levels",
    },
    {
      value: "100",
      label: "100 Level",
    },
    {
      value: "200",
      label: "200 Level",
    },
    {
      value: "300",
      label: "300 Level",
    },
    {
      value: "400",
      label: "400 Level",
    },
    {
      value: "500",
      label: "500 Level",
    },
  ],

  statuses: [
    {
      value: "",
      label: "All Status",
    },
    {
      value: "Active",
      label: "Active",
    },
    {
      value: "Graduated",
      label: "Graduated",
    },
    {
      value: "Deferred",
      label: "Deferred",
    },
    {
      value: "Suspended",
      label: "Suspended",
    },
    {
      value: "Withdrawn",
      label: "Withdrawn",
    },
  ],
};

export const students = [
  {
    id: 1,
    matricNumber: "UI/2021/001",
    fullName: "Adebayo Samuel",
    email: "adebayo.samuel@ui.edu.ng",
    phone: "+2348011111111",
    faculty: "Technology",
    department: "Agricultural Engineering",
    level: "400",
    admissionYear: "2021",
    session: "2024/2025",
    status: "Active",
    cgpa: 4.52,
    creditsEarned: 118,
    outstandingCourses: 0,
    academicStanding: "Excellent",
  },

  {
    id: 2,
    matricNumber: "UI/2022/002",
    fullName: "Grace Okafor",
    email: "grace.okafor@ui.edu.ng",
    phone: "+2348022222222",
    faculty: "Technology",
    department: "Civil Engineering",
    level: "300",
    admissionYear: "2022",
    session: "2024/2025",
    status: "Active",
    cgpa: 4.18,
    creditsEarned: 86,
    outstandingCourses: 1,
    academicStanding: "Very Good",
  },

  {
    id: 3,
    matricNumber: "UI/2021/003",
    fullName: "David Bello",
    email: "david.bello@ui.edu.ng",
    phone: "+2348033333333",
    faculty: "Technology",
    department: "Mechanical Engineering",
    level: "400",
    admissionYear: "2021",
    session: "2024/2025",
    status: "Active",
    cgpa: 3.74,
    creditsEarned: 111,
    outstandingCourses: 2,
    academicStanding: "Good",
  },

  {
    id: 4,
    matricNumber: "UI/2020/004",
    fullName: "Esther James",
    email: "esther.james@ui.edu.ng",
    phone: "+2348044444444",
    faculty: "Technology",
    department: "Electrical Engineering",
    level: "500",
    admissionYear: "2020",
    session: "2024/2025",
    status: "Active",
    cgpa: 4.71,
    creditsEarned: 146,
    outstandingCourses: 0,
    academicStanding: "Excellent",
  },

  {
    id: 5,
    matricNumber: "UI/2023/005",
    fullName: "John Musa",
    email: "john.musa@ui.edu.ng",
    phone: "+2348055555555",
    faculty: "Technology",
    department: "Computer Engineering",
    level: "200",
    admissionYear: "2023",
    session: "2024/2025",
    status: "Active",
    cgpa: 3.41,
    creditsEarned: 43,
    outstandingCourses: 3,
    academicStanding: "Fair",
  },

  {
    id: 6,
    matricNumber: "UI/2020/006",
    fullName: "Mercy Adeola",
    email: "mercy.adeola@ui.edu.ng",
    phone: "+2348066666666",
    faculty: "Technology",
    department: "Agricultural Engineering",
    level: "500",
    admissionYear: "2020",
    session: "2024/2025",
    status: "Active",
    cgpa: 4.36,
    creditsEarned: 143,
    outstandingCourses: 1,
    academicStanding: "Very Good",
  },

  {
    id: 7,
    matricNumber: "UI/2021/007",
    fullName: "Samuel Ibrahim",
    email: "samuel.ibrahim@ui.edu.ng",
    phone: "+2348077777777",
    faculty: "Technology",
    department: "Civil Engineering",
    level: "400",
    admissionYear: "2021",
    session: "2024/2025",
    status: "Deferred",
    cgpa: 3.02,
    creditsEarned: 98,
    outstandingCourses: 5,
    academicStanding: "Fair",
  },

  {
    id: 8,
    matricNumber: "UI/2022/008",
    fullName: "Ruth Emmanuel",
    email: "ruth.emmanuel@ui.edu.ng",
    phone: "+2348088888888",
    faculty: "Technology",
    department: "Mechanical Engineering",
    level: "300",
    admissionYear: "2022",
    session: "2024/2025",
    status: "Active",
    cgpa: 3.89,
    creditsEarned: 82,
    outstandingCourses: 2,
    academicStanding: "Good",
  },

  {
    id: 9,
    matricNumber: "UI/2023/009",
    fullName: "Daniel Ojo",
    email: "daniel.ojo@ui.edu.ng",
    phone: "+2348099999999",
    faculty: "Technology",
    department: "Electrical Engineering",
    level: "200",
    admissionYear: "2023",
    session: "2024/2025",
    status: "Active",
    cgpa: 4.04,
    creditsEarned: 48,
    outstandingCourses: 0,
    academicStanding: "Very Good",
  },

  {
    id: 10,
    matricNumber: "UI/2024/010",
    fullName: "Chioma Nwosu",
    email: "chioma.nwosu@ui.edu.ng",
    phone: "+2348010101010",
    faculty: "Technology",
    department: "Computer Engineering",
    level: "100",
    admissionYear: "2024",
    session: "2024/2025",
    status: "Active",
    cgpa: 4.61,
    creditsEarned: 22,
    outstandingCourses: 0,
    academicStanding: "Excellent",
  },
];
